taskID: 47782a84-8546-4c69-9b0d-271c1610b7dc
dthTaskTableName: DataTransferHub-APITaskTable658DE9FE-74MXIZUG8YGP


options:
  chunkSize: 5
  multipartThreshold: 10
  maxKeys: 1000
  messageBatchSize: 10
  finderDepth: 0
  finderNumber: 1
  workerNumber: 4
  includeMetadata: false
